project:
  type: website

website:
  title: "StudyNotes"
  favicon: image/bookcover.png
  twitter-card: true
  site-url: https://kawa5902.github.io/StudyNote
  google-analytics: "G-BDJN77QH1T"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "教育測定"
        href: IRT/irt_index.qmd
      - text: "社会調査"
        href: SURVEY/survey_index.qmd
      - text: "情報機器"
        href: ICT/ict_index.qmd
      - text: "覚え書き"
        href: BLOG/index.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
